env:
  node: true
  es2021: true
extends:
  - standard-with-typescript
parserOptions:
  ecmaVersion: latest
  sourceType: module
  project:
    - tsconfig.json
rules:
  indent:
    - error
    - 2
    - ignoredNodes:
        - FunctionExpression > .params[decorators.length > 0]
        - FunctionExpression > .params > :matches(Decorator, :not(:first-child))
        - ClassBody.body > PropertyDefinition[decorators.length > 0] > .key

  object-curly-spacing: error

  no-console: warn
  no-debugger: warn

  arrow-parens:
    - error
    - as-needed

  "@typescript-eslint/indent":
    - error
    - 2
    - ignoredNodes:
        - FunctionExpression > .params[decorators.length > 0]
        - FunctionExpression > .params > :matches(Decorator, :not(:first-child))
        - ClassBody.body > PropertyDefinition[decorators.length > 0] > .key

  "@typescript-eslint/no-unsafe-argument": 0
  "@typescript-eslint/no-floating-promises": 0
  "@typescript-eslint/prefer-nullish-coalescing": 0
  "@typescript-eslint/strict-boolean-expressions": 0
  "@typescript-eslint/consistent-type-assertions": 0
  "@typescript-eslint/consistent-type-definitions": 0
  "@typescript-eslint/consistent-indexed-object-style": 0
